/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ArchivosGUI.java
 *
 * Created on 04-28-2010, 05:22:50 PM
 */
package interfaces;

import Archivos.Archivos;
import java.awt.event.ItemEvent;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.text.Document;
import javax.swing.text.PlainDocument;

/**
 *
 * @author Steve
 */
public class ArchivosGUI extends javax.swing.JDialog {

    Archivos archivos = new Archivos();

    /** Creates new form ArchivosGUI */
    public ArchivosGUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        distComboBox.setSelectedIndex(-1);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        distComboBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        archivosList = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        archivoTextPane = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        distComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Distribucion Geometrica", "Distribucion Poisson", "Distribucion Uniforme", "Distribucion Exponencial", "Distribucion  Normal" }));
        distComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                distComboBoxItemStateChanged(evt);
            }
        });
        distComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                distComboBoxActionPerformed(evt);
            }
        });

        jLabel1.setText("Seleccion el tipo de distribucion:");

        jSplitPane1.setDividerLocation(150);
        jSplitPane1.setContinuousLayout(true);
        jSplitPane1.setOneTouchExpandable(true);

        archivosList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Seleccione primero la distribucion de probabilidad" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        archivosList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        archivosList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                archivosListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(archivosList);

        jSplitPane1.setLeftComponent(jScrollPane1);

        jScrollPane2.setViewportView(archivoTextPane);

        jSplitPane1.setRightComponent(jScrollPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(distComboBox, 0, 290, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(distComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void distComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_distComboBoxItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            //JOptionPane.showMessageDialog(null, "Seleccionado: " + distComboBox.getSelectedItem().toString());
            mostrarListadoArchivos(distComboBox.getSelectedIndex());
        }
    }//GEN-LAST:event_distComboBoxItemStateChanged

    private void distComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_distComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_distComboBoxActionPerformed

    private void archivosListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_archivosListValueChanged
        try {
            new Archivos().leerArchivo(archivosList.getSelectedValue().toString());
            archivoTextPane.setText(null);
        } catch (IOException ex) {
            System.out.println(ex);
        }

    }//GEN-LAST:event_archivosListValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                ArchivosGUI dialog = new ArchivosGUI(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane archivoTextPane;
    private javax.swing.JList archivosList;
    private javax.swing.JComboBox distComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables

    private void mostrarListadoArchivos(int tipo) {
        String[] arch = null;
        switch (tipo) {
            case 0:
                arch = archivos.listarArchivos("GEO");
                break;
            case 1:
                arch = archivos.listarArchivos("POI");
                break;
            case 2:
                arch = archivos.listarArchivos("UNI");
                break;
            case 3:
                arch = archivos.listarArchivos("EXP");
                break;
            case 4:
                arch = archivos.listarArchivos("NOR");
                break;
        }
        DefaultListModel dlm = new DefaultListModel();
        for (int i = 0; i < arch.length; i++) {
            dlm.addElement(arch[i]);

        }
        archivosList.setModel(dlm);
        archivosList.updateUI();
    }
}
